### ISSUE TITLE
Assigning what IPs to scan

### ISSUE THREAD

**Issue by jealdridge** [GordonVi/ip_scan#1]
it doesnt not work for my network. is there anything else that i would need to adjust for this script besides what Vlan/IPs i want it to look at.

**Comment by GordonVi** [comment]
If your on Windows:

type "ipconfig /all" in the CMD Prompt

You will see something like:

   IPv4 Address. . . . . . . . . . . : 1.2.3.4 (Preferred)

Line 34 of the script needs to mimic this so it looks like:

"1.2.3.$a" # set the first 3 octlets.

**Comment by GordonVi** [comment]
On Linux, the command is "ifconfig"

**Comment by GordonVi** [comment]
On the network side, this script using "ping."

Unlike servers that use port numbers, like HTTP using port 80, ping uses something called ICMP. If you have a firewall, or ACL rules between VLANs, you may be blocking ICMP requests.  
  
You can test this by trying to ping another known device on the network.  If you know the device is on the network and you can't ping it, then your network or firewall is blocking ICMP requests. (or blocking ping)
 
 Windows Firewall can block ICMP. You may need to disable it.
 
 Or, you can test by using NMAP and try to connect to well known ports like 139 (file sharing) (This is not in the script, but you can modify the script to do this.)

**Comment by ghost** [comment]
Hi.  I just found this.  It's awesome.  I really like the console output.  Is there anyway to make it where it can go through not only the 4th octet but also the 3rd.  so example: 10.170.x.x and it would scan that whole range for 10.170.   I would love it if you could help me create this.  Thanks for sharing your creation.

**Comment by GordonVi** [comment]
Yup, replace the 10.0.0.$a line with:

For ($b=56; $b -le 63; $b++) {

"10.0.$b.$a"

}

**Comment by ghost** [comment]
So add this inside the first for loop?  
thank you

**Comment by ghost** [comment]
honestly this is the best ip scanner i have found.  you did a great job making it.

**Comment by GordonVi** [comment]
Yup. Your making a nested loop. Order doesn't matter since threads report
out of order.
